# Generated by Django 4.1.2 on 2022-10-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesshall',
            name='capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
