# Generated by Django 4.1.2 on 2022-10-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_fitnesshall_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnesshallappointments',
            old_name='fitnessHall',
            new_name='fitness_hall',
        ),
    ]
